apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yky4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-yky4@sha256:7e67e19d5d31ac8f57df9da97fd05ce0dcd4cce4a20811a14f04024d2400c501
        name: my-nodejs
        resources: {}
status: {}
